### ISSUE TITLE
Lightbox is empty

### ISSUE THREAD

**Issue by johannes-bittner** [1up-lab/contao-points-of-interest#8] opened 2020-11-19 10:21 UTC
Contao 4.9.9 (cyon), release 2.1.2: lightbox ist empty (no content)  
The lightbox overlay just zooms in, but without content. Tested in two installations ... (sorry for being so persistent ...)

![grafik](https://user-images.githubusercontent.com/1597697/99653294-22d87880-2a59-11eb-93c7-3a7240c30ed2.png)

**Comment by kikmedia** [comment] 2020-11-19 10:34
Confirmed. The point ist that the variable $content is empty, even if there is a record in tl_content for it. There, $poi_id is empty.

**Comment by bytehead** [comment] 2020-11-20 10:42
Should be fixed in `2.1.3`.

**Closed by bytehead** 2020-11-20 10:42 UTC
Labels: bug

**Comment by kikmedia** [comment] 2020-11-20 10:54
Works for me, thanks a lot. How may I find your whishlist?

**Comment by bytehead** [comment] 2020-11-20 11:12
I don't have any 🙃 Let's have a beer at the next Contao Conference|Camp 😎

**Comment by kikmedia** [comment] 2020-11-20 11:13
Sounds reasonable. As long as we stay with beer, I will be fine with that.
